EZMS2RSS:
  LOCAL_TMP_ROOT_PATH: 'C:/Projects/ezms2rss/tmp/' #作業用エクセルの保存先など
EXCEL:
  EXE_PATH : 'C:/Program Files/Microsoft Office/root/Office16/EXCEL.EXE' #エクセルの実体
  ADDIN_PATH: 'C:/Users/<<user>>/AppData/Local/MarketSpeed2/Download/rss/MarketSpeed2_RSS_64bit.xll' #マケスピIIのアドイン保存先
RAKUTEN:
  MS2_ROOT_PATH: 'C:/Users/<<user>>/AppData/Local/MarketSpeed2/Bin' #マケスピII配下のBin
